return {
    Dark = {
        Name = "Dark",
        Accent = "#18181b",
        Outline = "#FFFFFF",
        Text = "#FFFFFF",
        Placeholder = "#999999",
        Background = "#0e0e10",
        Button = "#52525b",
        Icon = "#a1a1aa",
    },
    Light = {
        Name = "Light",
        Accent = "#FFFFFF",
        Outline = "#09090b",
        Text = "#000000",
        Placeholder = "#777777",
        Background = "#e4e4e7",
        Button = "#18181b",
        Icon = "#a1a1aa",
    },
    Rose = {
        Name = "Rose",
        Accent = "#881337",
        Outline = "#FFFFFF",
        Text = "#FFFFFF",
        Placeholder = "#6B7280",
        Background = "#4c0519",
        Button = "#52525b",
        Icon = "#a1a1aa",
    },
    Plant = {
        Name = "Plant",
        Accent = "#365314",
        Outline = "#FFFFFF",
        Text = "#e6ffe5",
        Placeholder = "#7d977d",
        Background = "#1a2e05",
        Button = "#52525b",
        Icon = "#a1a1aa",
    },
    Red = {
        Name = "Red",
        Accent = "#7f1d1d",
        Outline = "#FFFFFF",
        Text = "#ffeded",
        Placeholder = "#977d7d",
        Background = "#450a0a",
        Button = "#52525b",
        Icon = "#a1a1aa",
    },
    Indigo = {
        Name = "Indigo",
        Accent = "#312e81",
        Outline = "#FFFFFF",
        Text = "#ffeded",
        Placeholder = "#977d7d",
        Background = "#1e1b4b",
        Button = "#52525b",
        Icon = "#a1a1aa",
    },
    Moonlight = {
        Name = "Moonlight",
        Accent = "#92a6f6",           
        Outline = "#f5f7fa",          
        Text = "#f8fafc",             
        Placeholder = "#bfc7d6",      
        Background = "#2b3146",       
        Button = "#3c4364",           
        Icon = "#bbcfff",             
    },
    Midnight = {
        Name = "Midnight",
        Accent = "#232946",           
        Outline = "#d3d6db",
        Text = "#e0e4ed",
        Placeholder = "#8a99b4",
        Background = "#121629",       
        Button = "#393a56",
        Icon = "#bbbdde",
    },
    Summer = {
        Name = "Summer",
        Accent = "#ffd23f",           
        Outline = "#245501",          
        Text = "#264d21",             
        Placeholder = "#d7bc85",      
        Background = "#fffbeb",       
        Button = "#ffb54c",           
        Icon = "#ffd23f",             
    },
}
